<a href="https://colab.research.google.com/github/suhapatil2005-ctrl/Pythonprogams/blob/main/numpypython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [4]:
arr_lst1=np.array(list1)
print(arr_lst1)

[1 2 3]


In [5]:
list1=[1,2,3,4]
list2=[3,5,6,7]

arr_lst=np.array([list1,
                  list2])
print("2 dimensional array",arr_lst)

2 dimensional array [[1 2 3 4]
 [3 5 6 7]]


In [6]:
list1=[1,2,3,4]
list2=[3,5,6,7]


arr_lst=np.array([list1, list2])
print("two dimensional array\n",arr_lst)
print("dimension of array is: ",arr_lst.ndim)

two dimensional array
 [[1 2 3 4]
 [3 5 6 7]]
dimension of array is:  2


In [7]:
list1=[1,2,3,4]
list2=[3,5,6,7]
list3=[5,6,4,3]


arr_lst2=np.array([[list1, list2 , list3]])
print("two dimensional array\n",arr_lst2)

two dimensional array
 [[[1 2 3 4]
  [3 5 6 7]
  [5 6 4 3]]]


In [8]:
print(arr_lst2.ndim)

3


In [9]:
arr1=np.array([[[0.1,0.2,0.3,0.4], [0.4,0.5,0.6,0.4],  [0.3,0.4,0.5,0.6], [0.3,0.6,0.7,0.8]]])
print(arr1)

print("shape",arr1.shape)
print("size",arr1.size)
print("dtype",arr1.dtype)
print("n_dim",arr1.ndim)

[[[0.1 0.2 0.3 0.4]
  [0.4 0.5 0.6 0.4]
  [0.3 0.4 0.5 0.6]
  [0.3 0.6 0.7 0.8]]]
shape (1, 4, 4)
size 16
dtype float64
n_dim 3


In [10]:
arr2=np.array([1,2,3,4])
print(arr2)

print("shape:",arr2.shape)
print("size:",arr2.size)
print("dtype:",arr2.dtype)
print("n_dim:",arr2.ndim)



[1 2 3 4]
shape: (4,)
size: 4
dtype: int64
n_dim: 1


# ***Array initialize methods:***

In [11]:
#zeros array

zeros_array=np.zeros((2,3))
print("zeroes array:\n",zeros_array)


#ones arrray

one_array=np.ones((2,3))
print("ones array:\n",one_array)

#full arrray
full_array=np.full((3,4),5)
print("full array:\n",full_array)

#identity matrix

identity_array=np.eye(3)
print("identity matrix:\n",identity_array)


#empty array

em_array=np.empty((2))
print("empty array:\n",em_array)

#evenly spaced array
print("evenly spaced array:\n",np.arange(2,10,1))

#specific number of equaly spaced values between a range

print("evenly spaced:\n",np.linspace(1,20,5))



zeroes array:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
empty array:
 [7.74860419e-304 7.74860419e-304]
evenly spaced array:
 [2 3 4 5 6 7 8 9]
evenly spaced:
 [ 1.    5.75 10.5  15.25 20.  ]


In [12]:
#random array

print(np.random.randint(0, 100, size=(3,4), dtype=np.int64))



[[59  1 51  4]
 [ 2 60  2 80]
 [54 81 26 29]]


In [13]:
print(np.random.randint(0,100, size=(3,4)))

[[33 66 23 76]
 [98 20 46 19]
 [29 19 93 89]]


# ***array initialize and slicing***

In [14]:
a=np.array([1,2,3,4,5,3,4,4,6,4])
print(a)
print(len(a))

[1 2 3 4 5 3 4 4 6 4]
10


In [15]:
print(a[2])

#print(a[:5])

#print(a[1:9:2])

print(a[-1:-9:-2])

3
[4 4 3 4]


In [16]:
#2 dimeniosIONAL ARRAY

two_aray=np.array([[1,2,3,4,5], [5,6,7,8,5]])
print(two_aray,"\n")


print(two_aray[1],"\n")
print(two_aray[0])

[[1 2 3 4 5]
 [5 6 7 8 5]] 

[5 6 7 8 5] 

[1 2 3 4 5]
